apiVersion: v1
kind: Secret
metadata:
  name: tencentcloud-cloud-controller-manager-config
  namespace: kube-system
data:
  TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_REGION: "ap-shanghai"
  TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_SECRET_ID: "QUtJRHpwMDFtVFd4bEpsQU5LYlE1WUQyV1FHVVlQWHRwVVhFCg=="
  TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_SECRET_KEY: "VVFZNVJXUjJNVlJIdk5aY2RYTWtQV1hkR2hUN09GRjEK" 
  TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_CLUSTER_ROUTE_TABLE: "	rtb-oo956y0f" 
  TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_VPC_ID: "vpc-ip21y27i"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tencentcloud-cloud-controller-manager
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: tencentcloud-cloud-controller-manager
    spec:
      dnsPolicy: Default
      tolerations:
        - key: "node.cloudprovider.kubernetes.io/uninitialized"
          value: "true"
          effect: "NoSchedule"
        - key: "node.kubernetes.io/network-unavailable"
          value: "true"
          effect: "NoSchedule"
      containers:
      - image: ccr.ccs.tencentyun.com/library/tencentcloud-cloud-controller-manager:latest
        name: tencentcloud-cloud-controller-manager
        command:
          - /bin/tencentcloud-cloud-controller-manager
          - --cloud-provider=tencentcloud # 指定 cloud provider 为 tencentcloud
          - --allocate-node-cidrs=true # 指定 cloud provider 为 tencentcloud 为 node 分配 cidr
          - --cluster-cidr=192.168.0.0/20 # 集群 pod 所在网络，需要提前创建
          - --master=<KUBERNETES_MASTER_INSECURE_ENDPOINT> # master 的非 https api 地址
          - --configure-cloud-routes=true
          - --allow-untagged-cloud=true
        env:
          - name: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_REGION
            valueFrom:
              secretKeyRef:
                name: tencentcloud-cloud-controller-manager-config
                key: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_REGION
          - name: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_SECRET_ID
            valueFrom:
              secretKeyRef:
                name: tencentcloud-cloud-controller-manager-config
                key: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_SECRET_ID
          - name: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: tencentcloud-cloud-controller-manager-config
                key: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_SECRET_KEY
          - name: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_CLUSTER_ROUTE_TABLE
            valueFrom:
              secretKeyRef:
                name: tencentcloud-cloud-controller-manager-config
                key: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_CLUSTER_ROUTE_TABLE
          - name: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_VPC_ID
            valueFrom:
              secretKeyRef:
                name: tencentcloud-cloud-controller-manager-config
                key: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_VPC_ID